FROM node:20-alpine

WORKDIR /app/

RUN corepack enable && corepack prepare pnpm@latest --activate

COPY package.json ./
COPY prisma ./prisma

RUN pnpm install

COPY . ./

CMD ["sh", "-c", "pnpm prisma migrate dev && pnpm run start:dev"]
