FROM node:18-alpine

WORKDIR /app

# Instalar dependências
COPY package*.json ./
RUN npm install

# Copiar todo o projeto
COPY . .

# Expor porta padrão do NestJS
EXPOSE 3000

# Rodar em modo dev com hot reload
CMD ["npx", "ts-node-dev", "--respawn", "--transpile-only", "src/main.ts"]
